"""stage14 user persona and transformation domain

Revision ID: 5c3a91a4c003
Revises: ba3c6a475d25
Create Date: 2026-09-12 01:51:56.978538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3a91a4c003'
down_revision: Union[str, Sequence[str], None] = 'ba3c6a475d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'planned', 'generating', 'completed', 'failed')", name='ck_transformations_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User-owned transformation workflow'
    )
    op.create_index(op.f('ix_transformations_user_id'), 'transformations', ['user_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_blueprints_version'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'output_format', 'version', name='uq_blueprints_transformation_format_version'),
    comment='Versioned blueprint for one output format'
    )
    op.create_index(op.f('ix_blueprints_transformation_id'), 'blueprints', ['transformation_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name='ck_deliverables_revision'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'output_format', 'revision', name='uq_deliverables_transformation_format_revision'),
    comment='Generated deliverable revision for one output format'
    )
    op.create_index(op.f('ix_deliverables_transformation_id'), 'deliverables', ['transformation_id'], unique=False)
    op.create_table('transformation_output_formats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformation_id', 'output_format', name='uq_transformation_output_formats_transformation_format'),
    comment='Output format selection with generation parameter snapshot'
    )
    op.create_index(op.f('ix_transformation_output_formats_transformation_id'), 'transformation_output_formats', ['transformation_id'], unique=False)
    op.create_table('transformation_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('input_file_id', sa.UUID(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('file', 'text', 'url')", name='ck_transformation_sources_source_type'),
    sa.ForeignKeyConstraint(['input_file_id'], ['input_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ingestible source attached to a transformation workflow'
    )
    op.create_index('ix_transformation_sources_input_file', 'transformation_sources', ['input_file_id'], unique=False)
    op.create_index(op.f('ix_transformation_sources_transformation_id'), 'transformation_sources', ['transformation_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('organisation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'organisation')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_transformation_sources_transformation_id'), table_name='transformation_sources')
    op.drop_index('ix_transformation_sources_input_file', table_name='transformation_sources')
    op.drop_table('transformation_sources')
    op.drop_index(op.f('ix_transformation_output_formats_transformation_id'), table_name='transformation_output_formats')
    op.drop_table('transformation_output_formats')
    op.drop_index(op.f('ix_deliverables_transformation_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_blueprints_transformation_id'), table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_transformations_user_id'), table_name='transformations')
    op.drop_table('transformations')
    # ### end Alembic commands ###
